CREATE DATABASE VISTARA_DB;

USE VISTARA_DB;	

CREATE TABLE Flight(
	FlightId INT IDENTITY(20261,1) PRIMARY KEY,
	FlightCode VARCHAR(10) UNIQUE NOT NULL,
	FlightName VARCHAR(50) NOT NULL,
	Source VARCHAR(50) NOT NULL,
	Destination VARCHAR(50) NOT NULL,
	ArrivalTime TIME NOT NULL,
	DepartureTime TIME NOT NULL,
	IsDeleted BIT DEFAULT 0,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE FlightInventory(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FlightId INT NOT NULL,
	TravelDate DATE NOT NULL,

	ExecutiveSeats INT NOT NULL CHECK(ExecutiveSeats >= 0),
	ExecutiveFare DECIMAL(18,2) NOT NULL,
	
	BusinessSeats INT NOT NULL CHECK(BusinessSeats >= 0),
	BusinessFare DECIMAL(18,2) NOT NULL,
	
	EconomySeats INT NOT NULL CHECK(EconomySeats >= 0),
	EconomyFare DECIMAL(18,2) NOT NULL,
	
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE(),

	CONSTRAINT FK_FlightInventory_Flight FOREIGN KEY (FlightId) REFERENCES Flight(FlightId),
	UNIQUE (FlightId, TravelDate)
);

CREATE TABLE Booking(
	BookingId INT IDENTITY(1,1) PRIMARY KEY,
	FlightId INT FOREIGN KEY REFERENCES Flight(FlightId) NOT NULL,
	TravelDate DATE NOT NULL,
	TotalFare DECIMAL(10,2) NOT NULL,
	BookingStatus VARCHAR(20) CHECK(BookingStatus IN('BOOKED', 'CANCELLED', 'FAILED')) DEFAULT 'BOOKED',
	IsDeleted BIT DEFAULT 0,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE PassengerDetails(
	PassengerId INT IDENTITY(1,1) PRIMARY KEY,
	BookingId INT FOREIGN KEY REFERENCES Booking(BookingId) NOT NULL,
	FullName VARCHAR(100) NOT NULL,
	Address VARCHAR(200) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	FlightId INT FOREIGN KEY REFERENCES Flight(FlightId) NOT NULL,
	TravelDate DATE NOT NULL,
	SeatNo VARCHAR(10) NOT NULL,
	Class VARCHAR(20) CHECK(Class IN ('ECONOMY','BUSINESS','EXECUTIVE')) NOT NULL,
	IsDeleted BIT DEFAULT 0,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UNIQUE (FlightId, TravelDate, SeatNo)
);

CREATE TABLE Cancellation(
	CancellationId INT IDENTITY(1,1) PRIMARY KEY,
	BookingId INT FOREIGN KEY REFERENCES Booking(BookingId) NOT NULL,
	CancelDate DATETIME DEFAULT GETDATE(),
	RefundAmount DECIMAL(10,2) NOT NULL,
	Deduction DECIMAL(10,2) NOT NULL,
	Reason VARCHAR(200),
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UNIQUE (BookingId)
);

DROP TABLE Users;

CREATE TABLE Users(
	UserId INT IDENTITY(1,1) PRIMARY KEY,
	FullName VARCHAR(100) NOT NULL,
	UserName VARCHAR(50) UNIQUE NOT NULL,
	Email VARCHAR(100) UNIQUE NOT NULL,
	PasswordHash VARCHAR(255) NOT NULL,
	Role VARCHAR(20) NOT NULL CHECK(Role IN ('MANAGER', 'EMPLOYEE')),
	CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
	UpdatedAt DATETIME DEFAULT GETDATE() NOT NULL
);

