//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistaraAirLinesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightInventory
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public System.DateTime TravelDate { get; set; }
        public int ExecutiveSeats { get; set; }
        public decimal ExecutiveFare { get; set; }
        public int BusinessSeats { get; set; }
        public decimal BusinessFare { get; set; }
        public int EconomySeats { get; set; }
        public decimal EconomyFare { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
